name: Huecontrolmc
version: '${project.version}'
main: fr.dieuginette.huecontrolmc.Main
api-version: 1.19
authors: [ DieuGinette ]
description: Un plugin simple qui vous permet d'interagir avec philips hue à partir de Minecraft.
website: https://nathanblanchet.com/
